name: Ansible playbooks rulesets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  apply:
    uses: ./.github/workflows/rulesets-apply.yml
    with:
      search_query: 'org:digital-iq in:name gh-schedule archived:false fork:false'
      csv_path: rulesets/ansible-playbooks.csv
    secrets: inherit
